### PR TITLE
Merge persistent config ConfigMaps between Helm upgrades

### LINKED ISSUE #704: Consume BotKube configuration from values.yaml and commands
## Description

The configuration changes made via `@BotKube` commands are not persisted. As a result, when the Pod is restarted, we lost all changes. 

In K8s world, the Pod restarts are a normal thing, and we should be resistant to it.

## Acceptance Criteria

1. Research what's the best option here from UX and maintenance point of view. [1MD]
1. `@Botkube notifier stop/start` changes are persisted
1. `@BotKube filters disable/enable` changes are persisted
1. Persist source bindings
    - They override bindings from the configuration 
1. Support configuration for notifier, filter, source bindings during Helm install/upgrade and `@BotKube` commands
1. We don't add new features besides the persistency. For example, the `@BotKube filters disable/enable` command still can work globally.
1. E2E Tests
 - consider: ensure `@Botkube notify stop/start` doesn't restart the pod/
 - kill the pod and see whether notifier config / filter config is saved

define the filters configuration under `filters.kubernetes` in `values.yaml`

## Steps to reproduce

1. Install BotKube inside cluster 
4. Run `@BotKube notifier stop`
5. Kill the pod, e.g. `kubectl delete po -l app=botkube`
6. See that you get a new message on channel:
   >...and now my watch begins for cluster 'gke' ! :crossed_swords:

## Notes

If we use the existing one with global configuration, the Pod will be restarted, which is not needed because of that we can store the data in dedicated ConfigMap.

### PR DESCRIPTION
**Pull request by pkosiec**
## Description

Changes proposed in this pull request:

- Merge persistent config ConfigMaps between Helm upgrades

## Testing

Checkout this PR and export the following envs:

```bash
export WS_SLACK_BOT_TOKEN=""
export WS_SLACK_APP_TOKEN=""
```

Install BotKube:

```bash
cat > /tmp/values.yaml << ENDOFFILE
communications:
  'default-group':
    socketSlack:
      enabled: true
      botToken: "${WS_SLACK_BOT_TOKEN}"
      appToken: "${WS_SLACK_APP_TOKEN}"
      channels:
        'default':
          name: botkube-test
          notification:
            disabled: true
          bindings:
            executors:
              - kubectl-read-only
            sources:
              - k8s-events
        'second':
          name: botkube-demo
          bindings:
            executors:
              - kubectl-read-only
            sources:
              - k8s-events

settings:
  clusterName: dev
executors:
  'kubectl-read-only':
    kubectl:
      enabled: true
analytics:
  disable: true
image:
  repository: kubeshop/pr/botkube
  tag: '762-PR'
  pullPolicy: Always  
ENDOFFILE
helm install botkube ./helm/botkube -n botkube --create-namespace  -f /tmp/values.yaml
```

Get ConfigMaps:

```bash
kubectl get cm -n botkube botkube-runtime-config -oyaml
kubectl get cm -n botkube botkube-startup-config -oyaml
```

Run commands on `botkube-test` channel on Slack:

```
@BotKube filters disable NodeEventsChecker
```

```
@BotKube notifier start
```

Also, edit SourceBindings on the same channel:

```yaml
@BotKube edit SourceBindings
```

Wait for app restart.

Same for `botkube-demo channel:

```yaml
@BotKube edit SourceBindings
```

Wait for app restart.

See the ConfigMaps:

```bash
kubectl get cm -n botkube botkube-runtime-config -oyaml
kubectl get cm -n botkube botkube-startup-config -oyaml
```

Upgrade the installation:

```yaml
cat > /tmp/values-upgrade.yaml << ENDOFFILE
communications:
  'default-group':
    socketSlack:
      enabled: true
      botToken: "${WS_SLACK_BOT_TOKEN}"
      appToken: "${WS_SLACK_APP_TOKEN}"
      channels:
        'default':
          name: botkube-test
          notification: null # explicitly not use defaults from Helm chart
          bindings:
            executors: []
            sources: null # explicitly not use defaults from Helm chart
        'second':
          name: botkube-demo
          notification:
            disabled: true
          bindings:
            executors:
              - kubectl-read-only
            sources:
              - k8s-events
              - k8s-err-events

settings:
  clusterName: dev
executors:
  'kubectl-read-only':
    kubectl:
      enabled: true
analytics:
  disable: true
filters: null # explicitly not use defaults from Helm chart
image:
  repository: kubeshop/pr/botkube
  tag: '746-PR'
  pullPolicy: Always  
ENDOFFILE
helm upgrade botkube ./helm/botkube --namespace botkube -f /tmp/values-upgrade.yaml --wait
```

See the ConfigMaps again:

```bash
kubectl get cm -n botkube botkube-runtime-config -oyaml
kubectl get cm -n botkube botkube-startup-config -oyaml
```

You can also run rollback:

```bash
helm rollback -n botkube botkube
```

And the values will be restored to the ones from previous Helm release (changes to state set by commands will be gone).

## Related issue(s)

See #704

### CODE REVIEW

**Comment by pkosiec** [comment]
I wanted to write a few sentences about such behavior in our docs, but I'm not sure where is the correct place to do so 🤔 A new document under `Configuration` ([link](https://botkube.io/docs/next/configuration/)), e.g. `configuration/upgrade.md`? @ezodude Do you have any suggestions?

**Comment by ezodude** [comment]
@pkosiec ... off the top my head ...  

Have you seen the [Updating the configuration at runtime](https://botkube.io/docs/next/configuration/#updating-the-configuration-at-runtime) section. It closely relates to this, so it makes the [Configuration page](https://botkube.io/docs/next/configuration) a good place for this info.

We can have a new section entitled "How configuration is saved at runtime and during upgrades"?

If the explanation gets too big, maybe add a new page under the Configuration section "Saving configuration".

**Comment by pkosiec** [comment]
Good idea, thanks @ezodude! Will create another PR with docs soon, but this one is ready to review 🙂

**Review by ezodude — APPROVED** [review]
Tested locally - works. 👍

**Pull request merged**
