### PR TITLE
Update JSON schemas for all plugins

### PR DESCRIPTION
**Pull request by pkosiec**
## Description

Changes proposed in this pull request:

- Update JSON schemas for all plugins
   - Add password format for credentials
   - Ensure `log` is exposed everywhere
   - Ensure `additionalProperties` are enabled for plugins with more complex data
- Unify JSON schema definition across all plugins

## Testing

- rebuild your local plugins  `make build-plugins-single`
- run your local plugin index server `go run test/helpers/plugin_server.go`
- use `http://localhost:3010/botkube.yaml` as plugin repository for Botkube Cloud
- Create instance and see the plugin list. Enable all of them and see the YAML editor + UI forms.
   - See that all the propoerties are already filled-in in the yaml editor
   - See that the password fields are properly visible in UI form

image

### CODE REVIEW

**Comment by huseyinbabal** [comment]
@pkosiec 

Keptn and Doctor plugins has confidental data but they seem like plain text, any reason for that?

**Comment by pkosiec** [comment]
@huseyinbabal are you sure you're using the latest schemas and the latest UI? In the PR desc I posted a screenshot how it should look like

**Comment by huseyinbabal** [comment]
> @huseyinbabal are you sure you're using the latest schemas and the latest UI? In the PR desc I posted a screenshot how it should look like

I checkout this pr branch and built all the indexes, and using as botkube cloud plugin repository. I will double check and get back to you

**Review by huseyinbabal — APPROVED** [review]
Works as expected 🚀

**Pull request merged**
